#!/bin/sh -e

# $Id: setversion,v 1.1 2004/06/29 19:25:53 vanbaal Exp $
# $Source: /cvsroot/crm114/crm114/setversion,v $

# based upon mcl/mcl/setversion by Stijn van Dongen
# called in Makefile.am and in bootstrap

# used by man/include.zmm.in

# likely needs GNU date
date '+%e' > stamp.day
date '+%b' > stamp.month
date '+%Y' > stamp.year

